### ISSUE TITLE
[Bug] Module lib/impeccable-config.mjs missing

### ISSUE THREAD

**Issue by dsancalm** [pbakaus/impeccable#254]
## What happened?

Module lib/impeccable-config.mjs missing

## Steps to reproduce

1. Use /impeccable critique on react app
2. 
3. 

## Expected behavior

Working properly.

## Provider & environment

- **Provider** (Cursor / Claude Code / Gemini CLI / Codex / Copilot / Kiro / OpenCode):
- **Provider version**:  Claude code
- **OS**: macOS Tahoe 25

## Additional context

Installed via npx

**Comment by pbakaus** [comment]
Fixed in [skill-v3.7.1](https://github.com/pbakaus/impeccable/releases/tag/skill-v3.7.1).

**Root cause:** the bundled detector's `cli/main.mjs` imports `../../lib/impeccable-config.mjs`. In the source CLI that resolves to `cli/lib/impeccable-config.mjs`, but the skill build only copied `cli/engine/**` into the bundle, leaving that dependency behind. So `/impeccable critique` (and any detector-backed command) crashed on startup with `Cannot find module .../lib/impeccable-config.mjs`. Introduced in #252.

**Fix:** the detector bundler now copies out-of-bundle engine dependencies into the skill's `scripts/lib/`, and a new build test asserts every bundled script's relative imports resolve to another bundled file, so a future out-of-bundle dependency fails the build instead of reaching users.

Update to get the fix: `npx impeccable install` or `npx impeccable update`

Thanks for the clear report!
